# -*- coding: utf-8 -*-
"""cleanStyleCSVs.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tVPBgV4ByztpG10mTQ8oySbgaEhMXs92
"""

from collections import namedtuple
import pathlib
import PIL
import pandas as pd

from google.colab import drive
drive.mount('/content/drive')

root = "/content/drive/My Drive/HMC/2020-2021/FA20-CS121/CS121F20_ Team_1_Art/Photos/"
#root = "/content/drive/My Drive/CS Classes/CS 121/CS121F20_ Team_1_Art/Photos/"
train = pd.read_csv(root+"wikiart_csv/style_train.csv", header=None)
valid = pd.read_csv(root+"wikiart_csv/style_val.csv", header=None)

style_dict = {0: "Abstract_Expressionism", 1: "Action_painting", 2: "Analytical_Cubism",
              3: "Art_Nouveau", 4: "Baroque", 5: "Color_Field_Painting",
              6: "Contemporary_Realism", 7: "Cubism", 8: "Early_Renaissance",
              9: "Expressionism", 10: "Fauvism", 11: "High_Renaissance",
              12: "Impressionism", 13: "Mannerism_Late_Renaissance",
              14: "Minimalism", 15: "Naive_Art_Primitivism", 16: "New_Realism",
              17: "Northern_Renaissance", 18: "Pointillism", 19: "Pop_Art",
              20: "Post_Impressionism", 21: "Realism", 22: "Rococo",
              23: "Romanticism", 24: "Symbolism", 25: "Synthetic_Cubism",
              26: "Ukiyo_e" }

train_cleaned = []
Pandas = namedtuple("Pandas", "index pathname classname")
for row in train.itertuples():
  if (pathlib.Path(root+"Style/wikiart/"+row[1]).exists()):
    classed = Pandas(row[0], row[1], style_dict[row[2]])
    train_cleaned.append(classed)

trained_clean_df = pd.DataFrame(train_cleaned)

trained_clean_df.to_csv(path_or_buf=root+"wikiart_csv/style_train_clean.csv", 
                        columns=["pathname","classname"], index=None, header=None)

valid_cleaned = []
for row in valid.itertuples():
  if (pathlib.Path(root+"Style/wikiart/"+row[1]).exists()):
    classed = Pandas(row[0], row[1], style_dict[row[2]])
    valid_cleaned.append(classed)

valid_clean_df = pd.DataFrame(valid_cleaned)
valid_clean_df.to_csv(path_or_buf=root+"wikiart_csv/style_valid_clean.csv", columns=["pathname","classname"], index=None, header=None)